services:
  claudebox:
    build:
      context: .
      args:
        - REPO_URL=${REPO_URL}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - USE_CLAUDE_CREDENTIALS=${USE_CLAUDE_CREDENTIALS}
    ports:
      - "3000:3000"  # HTTP server
      - "3001:3001"  # WebSocket terminal
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    # volumes:
    #   # Don't mount workspace since it's baked into the image
    #   # Uncomment below to override with local workspace for development
    #   - ./workspace:/workspace
    stdin_open: true
    tty: true